### PR TITLE
Move to packaging@0.9

### PR DESCRIPTION
**Pull request by mlucool**
Please finish the following when submitting a pull request:

- [ ] Add a line to `History.md` briefly documenting the change.

If this is a release, additionally do the following:

- [ ] Update the dependencies in `package.json`
- [ ] Run `jlpm install` to update `yarn.lock`

Thanks!

### CODE REVIEW

**Review by ianhi — APPROVED** [review]
:+1:  contingent on the build passing

**Comment by mlucool** [comment]
I don't really understand the error here:
>Successfully installed jupyterlab-vim-0.13.6
Error: Process completed with exit code 1.

**Comment by mlucool** [comment]
@ianhi can you kick this off again? I *think* I fixed the build issue

**Comment by ianhi** [comment]
I wonder why it still thinks you're a first time contributor. We merged a PR from you already??

Also it look as though I was wrong in the last PR about how the automated version bumping work and we ended up on `0.13.6` instead of `0.14.0`. I don't think I have adequate rights to modify settings for that, so for now we'll need to manually bump to `0.14.0` (and then get auto bumped to `.0.14.1`...)



Also, is this a real failure or is this warning just causing CI to be unhappy?

> WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
> distutils: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m/UNKNOWN
> sysconfig: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m

**Comment by ianhi** [comment]
Would it help to move to using `build` since we aren't making an editable install?

**Comment by mlucool** [comment]
> I wonder why it still thinks you're a first time contributor. We merged a PR from you already??

No idea, but can you kick it off one more time? I only modified one of the github workflows last time, so I think copy/pasting it to the other should work too now.

>Also, is this a real failure or is this warning just causing CI to be unhappy?

I didn't know what that was, but I don't think it is the problem.

**Comment by ianhi** [comment]
This is good - but I can't seem to push to your fork to bump the version. I'd like to do that here before the automated release goes and makes a release of `0.13.7` so can you bump us to `0.14.0` and then I'll merge?

**Comment by mlucool** [comment]
Version has been bumped to 0.14.0

**Comment by ianhi** [comment]
Awesome - thanks @mlucool !

**Pull request merged**
